// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iivjxdisnjkjidfywyip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpdmp4ZGlzbmpramlkZnl3eWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTcwMzYsImV4cCI6MjA3MTU5MzAzNn0.PxU19pGp2Po8g_EERAs2HG60tf9DZ-0b2z567Rq_3VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});